#!/bin/bash

# Loop through visible files in the current directory
for file in ./*; do
    # Exclude README.md file
    if [[ "$file" != "./README.md" ]]; then
        # Copy the file to the parent directory
        cp "$file" ../
        echo "Copied: $file"
    fi
done

echo "Copy process completed."

